//  "use client"

// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Navbar from "@/components/common/Navbar";
// import Footer from "@/components/common/Footer";
// import {

//   QueryClient,
//   QueryClientProvider,
// } from '@tanstack/react-query'
// // Create a client
// const queryClient = new QueryClient()

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// // export const metadata: Metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased bg-mainbackground overflow-x-hidden`}
//       >
//         <QueryClientProvider client={queryClient}>
//           <Navbar />
//           {children}
//           <Footer />
//         </QueryClientProvider>
//       </body>
//     </html>
//   );
// }
// 'use client';

// import { useEffect, useState } from 'react';
// import { useRouter } from 'next/navigation';
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Navbar from "@/components/common/Navbar";
// import Footer from "@/components/common/Footer";
// import { QueryClient, QueryClientProvider } from '@tanstack/react-query';

// // Fonts
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// // Create a client
// const queryClient = new QueryClient();

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   const router = useRouter();
//   const [isAuthenticated, setIsAuthenticated] = useState<boolean | null>(null);

//   useEffect(() => {
//     const token = localStorage.getItem('token');
//     if (!token) {
//       router.push('/login'); // 🔁 redirect if not logged in
//     } else {
//       setIsAuthenticated(true); // ✅ allow rendering
//     }
//   }, []);

//   if (isAuthenticated === null) return null; // wait for auth check

//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-mainbackground overflow-x-hidden`}>
//         <QueryClientProvider client={queryClient}>
//           <Navbar />
//           {children}
//           <Footer />
//         </QueryClientProvider>
//       </body>
//     </html>
//   );
// }
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/common/Navbar";
import Footer from "@/components/common/Footer";
import QueryProvider from "@/components/providers/QueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Roomi AR",
  description: "Interior design AR platform",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-mainbackground overflow-x-hidden`}
      >
        <QueryProvider>
          <Navbar />
          {children}
          <Footer />
        </QueryProvider>
      </body>
    </html>
  );
}
